apiVersion: 1

datasources:
  - name: BEAM Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: beam_monitoring
    user: beam_user
    secureJsonData:
      password: beam_pass
    jsonData:
      sslmode: disable
      postgresVersion: 1500
    isDefault: true
    editable: true
